/**
 * Generates blur-up placeholders for everything in `public/media`.
 *
 *   node scripts/gen-blur.mjs
 *
 * Files under `public/` are served by path, not statically imported, so Next
 * cannot derive a `blurDataURL` for them the way it does for `import img from
 * "./photo.jpg"`. This bakes them at author time instead and writes a typed map
 * to `src/lib/media-blur.ts`, which `components/media.tsx` reads.
 *
 * Re-run it whenever a file in `public/media` is added or replaced — and note
 * the rule in CLAUDE.md: look at the picture before committing it.
 *
 * `sharp` arrives with Next (it is what the image optimizer uses), so there is
 * no extra dependency to install.
 */

import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import sharp from "sharp";

const MEDIA_DIR = join(process.cwd(), "public", "media");
const OUT_FILE = join(process.cwd(), "src", "lib", "media-blur.ts");

/**
 * 12px wide is the useful floor: enough to carry the image's colour masses and
 * horizon, small enough that every placeholder together stays under ~10 KB in
 * the client bundle. Next applies its own CSS blur on top, so detail here is
 * wasted bytes.
 */
const WIDTH = 12;
const QUALITY = 45;

const IMAGE = /\.(jpe?g|png)$/i;

async function main() {
  const entries = await readdir(MEDIA_DIR, { withFileTypes: true });
  const files = entries
    .filter((e) => e.isFile() && IMAGE.test(e.name))
    .map((e) => e.name)
    .sort();

  if (files.length === 0) {
    console.error(`No images found in ${MEDIA_DIR}`);
    process.exitCode = 1;
    return;
  }

  const lines = [];
  let bytes = 0;

  for (const name of files) {
    const buffer = await sharp(join(MEDIA_DIR, name))
      .resize(WIDTH, null, { fit: "inside" })
      .jpeg({ quality: QUALITY, chromaSubsampling: "4:2:0" })
      .toBuffer();

    const dataUrl = `data:image/jpeg;base64,${buffer.toString("base64")}`;
    bytes += dataUrl.length;

    lines.push(`  "/media/${name}": "${dataUrl}",`);
    console.log(`${name.padEnd(32)} ${String(buffer.length).padStart(5)} B`);
  }

  const file = `/**
 * Generated by \`scripts/gen-blur.mjs\` — do not edit by hand.
 *
 * Base64 ${WIDTH}px placeholders for every image in \`public/media\`, keyed by
 * the public path they are served from. Consumed by \`components/media.tsx\`.
 */
export const mediaBlur: Record<string, string> = {
${lines.join("\n")}
};
`;

  await writeFile(OUT_FILE, file, "utf8");

  console.log(
    `\n${files.length} placeholders → src/lib/media-blur.ts (${(bytes / 1024).toFixed(1)} KB)`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
